### ISSUE TITLE
Non functional with tracking blocker enabled on firefox

### ISSUE THREAD

**Issue by alxdb** [brobsc/tider#1]
Hey, saw your post on reddit and thought this is probably a better place for bug reports.

As the title says. OS is Arch Linux, Firefox version 74.0.1. It seems Firefox's built in content blocker is blocking the `.json?jsonp=jsonpCb` urls that you're using. You might consider forwarding the content from the backend, rather than fetching it in the frontend.

Nice design btw, reminds me of the minimalist style on hackernews.

**Comment by brobsc** [comment]
Using jsonp was a deliberate choice, otherwise I would need to setup oauth and a developer account with reddit. Also, requests made purely on the frontend makes a much quicker experience without data rerouting through my servers.

I also use Firefox (Dev) 74 with privacy settings on highest + ublocker enabled, and it works fine on my end. You might want to check if you have any other extension, although it still should be fine unless you're explicitly blocking reddit.com.

Also, the request should fail with non descriptive errors if you try to load a invalid url or otherwise private subreddit. Did you try something simple as https://www.betider.com/r/clojure/ ?

I'll try to reproduce and fix this. Thanks for the report!

**Comment by alxdb** [comment]
Hi, I can still recreate the issue with firefox dev (75.0b11 (64-bit)) no plugins installed. But only when selecting the "strict" setting for "enhanced tracking protection" in the privacy & security section of the browser settings. There is a warning about some sites breaking with that setting enabled, so I suppose this is somewhat expected.

Additionally looking at the error message, there is a "learn more" link, which takes me to this site `https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Privacy/Tracking_Protection` indicating that this is indeed due to firefox blocking the requests.

Just thought I'd let you know :) Good luck!

**Comment by brobsc** [comment]
Hey, thanks for following up. This has been a busy week for me.


I thought I had that setting enabled on my browser, but yeah, strict mode is way more... strict. 

That indeed seems to be the case. Well, not much I can do before updating my backend and setting up a reddit developer account. Good news is whitelisting just tider is enough (although it finds "reddit.com" as the culprit of privacy breaching).

I will put up a warning meanwhile, and again, thanks for reporting and following up with that. Appreciate it!

**Comment by brobsc** [comment]
Hey, a warning has been put in the latest version. You can preview it at https://www.betider.com/error/ , but it should trigger at any loading error.

This is temporary while I work at a proper backend. Thank you for your help!
